apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "capz.fullname" . }}-aad-pod-id-nmi-binding
  labels:
    cluster.x-k8s.io/provider: infrastructure-azure
    k8s-app: capz-aad-pod-id-nmi-binding
  {{- include "capz.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "capz.fullname" . }}-aad-pod-id-nmi-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "capz.fullname" . }}-manager'
  namespace: '{{ .Release.Namespace }}'